Repository Andy-Hoch/Sport-Buddy, pull requests merged in 2023-09, with the labels that each got.

#39 Maps implemented, multiple location map does not yet display
  app/assets/stylesheets/components/_index.scss
  app/assets/stylesheets/components/_map.scss
  app/controllers/sport_sessions_controller.rb
  app/javascript/controllers/map_controller.js
  app/javascript/controllers/map_list_toggle_controller.js
  app/models/sport_session.rb
  app/models/venue.rb
  app/views/layouts/application.html.erb
  app/views/shared/_menubar.html.erb
  app/views/sport_sessions/index.html.erb
  app/views/sport_sessions/show.html.erb
  db/migrate/20230901141921_remove_coordinates_from_sport_session.rb
  db/migrate/20230901142222_add_coordinates_to_venues.rb
  db/schema.rb
Labels: READY TO REVIEW

#51 Add Sport Session Form works...
  app/controllers/sport_sessions_controller.rb
  app/controllers/venues_controller.rb
  app/policies/venue_policy.rb
  app/views/sport_sessions/new.html.erb
  config/routes.rb
  test/controllers/venues_controller_test.rb
  test/policies/venue_policy_test.rb
Labels: READY TO REVIEW

#52 If I join a session, the Chat-Button will be displayed instead of the join button
  app/views/sport_sessions/show.html.erb
Labels: READY TO REVIEW

#54 Apple icon update
  app/assets/images/apple-icon-180x180.png
  app/views/layouts/application.html.erb
Labels: READY TO REVIEW

#58 Chatroom installation
  app/assets/stylesheets/components/_chatroom.scss
  app/javascript/controllers/chatroom_subscription_controller.js
  app/views/messages/_message.html.erb
Labels: WIP

#60 If you scroll down, the menu bar should not be hiding content anymore...
  app/assets/stylesheets/components/_index.scss
  app/assets/stylesheets/components/_list.scss
  app/assets/stylesheets/components/_menubar.scss
  app/assets/stylesheets/components/_session_list_map.scss
  app/views/shared/_menubar.html.erb
Labels: READY TO REVIEW

#63 Map on Show page is fixed!!!
  app/assets/stylesheets/components/_alert.scss
  app/assets/stylesheets/components/_chatroom.scss
  app/assets/stylesheets/components/_chatrooms_list.scss
  app/assets/stylesheets/components/_session_list_map.scss
  app/javascript/controllers/map_list_toggle_controller.js
  app/views/chatrooms/index.html.erb
  app/views/chatrooms/show.html.erb
  app/views/messages/_message.html.erb
  app/views/sport_sessions/index.html.erb
Labels: READY TO REVIEW

#68 In the SportSession Index there will be no sessions of the past.
  app/controllers/sport_sessions_controller.rb
Labels: READY TO REVIEW

#66 The Form on the Homepage has floating Labels - Consistency and so... :)
  app/views/pages/home.html.erb
Labels: READY TO REVIEW, Just Styling

#70 Popups in the Map work
  app/assets/stylesheets/components/_index.scss
  app/assets/stylesheets/components/_map.scss
  app/controllers/sport_sessions_controller.rb
  app/javascript/controllers/map_controller.js
  app/views/sport_sessions/_map_details.html.erb
  app/views/sport_sessions/_map_marker.html.erb
Labels: READY TO REVIEW

#67 Inserted validations though more work needed
  Gemfile.lock
  app/assets/stylesheets/application.scss
  app/javascript/controllers/flatpickr_controller.js
  app/models/sport_session.rb
  app/views/sport_sessions/new.html.erb
Labels: WIP

#81 Show page update
  app/assets/stylesheets/components/_avatar_banner.scss
  app/assets/stylesheets/components/_session_card.scss
  app/controllers/sport_sessions_controller.rb
  app/views/sport_sessions/show.html.erb
Labels: READY TO REVIEW

#40 Sessions Cards Update
  app/assets/stylesheets/components/_chatroom.scss
  app/views/chatrooms/show.html.erb
  app/views/pages/_session_card.html.erb
  app/views/sport_sessions/_session_card.html.erb
  app/views/sport_sessions/_session_card_1.html.erb
Labels: READY TO REVIEW

#84 Card-Styling on the Homepage is Fixed
  app/assets/stylesheets/components/_category_card.scss
Labels: READY TO REVIEW
